test: implements unit test CreateGameController

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -26,15 +26,15 @@ jobs:
       run: yarn lint
 
     - name: Run test
-      run: yarn test
+      run: yarn test --coverage
 
-    - name: Test Report
-      uses: dorny/test-reporter@v1
-      if: success() || failure()
-      with:
-        name: Test Results
-        path: ${{ github.workspace }}/reports/test-results
-        reporter: jest-junit
+    # - name: Test Report
+    #   uses: dorny/test-reporter@v1
+    #   if: success() || failure()
+    #   with:
+    #     name: Test Results
+    #     path: ${{ github.workspace }}/reports/test-results
+    #     reporter: jest-junit
 
   sonarcloud:
     name: SonarCloud
